server:
  port: 7840

# mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志

logging:
  level:
    t.uni.service.mapper: warn
    t.uni.service.controller: warn
    t.uni.service.service: warn
    root: warn
  pattern:
    dateformat: HH:mm:ss:SSS
#  file:
#    path: "logs/${spring.application.name}"
#    name: "logs/${spring.application.name}"

# 线上禁用文档
knife4j:
  enable: true
  production: true

#  rabbitmq:
#    host: ${t.uni.rabbitmq.host}
#    port: ${t.uni.rabbitmq.port}
#    username: ${t.uni.rabbitmq.username}
#    password: ${t.uni.rabbitmq.password}
#    virtual-host: ${t.uni.rabbitmq.virtual-host}
#    publisher-confirm-type: correlated # 交换机确认
#    publisher-returns: true # 队列确认
#    listener:
#      simple:
#        acknowledge-mode: manual # 手动处理消息
#    connection-timeout: 1s # 设置MQ连接超时时间
#    template:
#      retry:
#        enabled: true # 失败重试
#        initial-interval: 1000ms # 失败后初始时间
#        multiplier: 1 # 失败后下次等待时长倍数 initial-interval * multiplier
#        max-attempts: 3 # 最大重试次数

t.uni:
  master:
    host: ${T_UNI_ADMIN_DB_HOST:localhost}
    port: ${T_UNI_ADMIN_DB_PORT:3306}
    database: ${T_UNI_ADMIN_DB_NAME:tuni_admin}
    username: ${T_UNI_ADMIN_DB_USERNAME:root}
    password: ${T_UNI_ADMIN_DB_PASSWORD:change_me}

  redis:
    host: ${T_UNI_ADMIN_REDIS_HOST:localhost}
    port: ${T_UNI_ADMIN_REDIS_PORT:6379}
    database: ${T_UNI_ADMIN_REDIS_DATABASE:0}
    password: ${T_UNI_ADMIN_REDIS_PASSWORD:}
