wx:
  miniapp:
    appid: ${WX_MINIAPP_APPID:}
    secret: ${WX_MINIAPP_SECRET:}
    token: ${WX_MINIAPP_TOKEN:}
    aesKey: ${WX_MINIAPP_AES_KEY:}
    msgDataFormat: JSON

  auth:
    login-identifier: ${WX_AUTH_LOGIN_IDENTIFIER:MA_OPEN_ID}
